### ISSUE TITLE
`Type 'WebAccessFS' is not assignable to type 'FileSystem | Promise<FileSystem>'`

### ISSUE THREAD

**Issue by yoursunny** [zen-fs/dom#18]
**WebAccess** is unusable in TypeScript due to type mismatch.

```ts
import { configure, InMemory } from "@zenfs/core";
import { WebAccess } from "@zenfs/dom";

await configure({
    mounts: {
        '/M': InMemory,
        '/W': {
            backend: WebAccess,
            handle: await navigator.storage.getDirectory(),
        },
    }
});
```

```text
Type '{ readonly name: "WebAccess"; readonly options: { readonly handle: { readonly type: "object"; readonly required: true; readonly description: "The directory handle to use for the root"; }; }; readonly isAvailable: () => boolean; readonly create: (options: WebAccessOptions) => WebAccessFS; }' is not assignable to type 'Backend<FileSystem, object>'.
  The types returned by 'create(...)' are incompatible between these types.
    Type 'WebAccessFS' is not assignable to type 'FileSystem | Promise<FileSystem>'.
      Type 'WebAccessFS' is missing the following properties from type 'FileSystem': ready, renameSync, statSync, openFileSync, and 9 more.
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ts=5.5.4#code/JYWwDg9gTgLgBAbzgYwgOwGbAOYFcoCmANHAJJoCyBI0AnnAL5wZQQhwBEAAgF4GYBnAPSpCHANwAoUJFiI4AdQIAjAILJkBAQMbNW7bn0FCAJmwmTJAQwDuV4PFSYc+AgAoEkuN7g1caGAEALkQvH3CAciEKCJDyKhooWiIw8O8ohVjQtJy4ZStkAGt+ExClNQ0tARTctIALKzQTABsCENt7eDQrADccKxhoADoBQagrbAIhyZgAEWBCZDHaNwBKGtyGDe8GSQZVqSA)

**Comment by james-pre** [comment]
This seems like the type for the `Async` mixin did not load correctly.

Looking into it further, I find this error with IntelliSense:
```
Cannot find module '@zenfs/core/mixins/shared.js' or its corresponding type declarations.
  There are types at '<project>/node_modules/@zenfs/core/dist/mixins/shared.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(2307)
```

This error only appears in the built code, not source, which may help explain why it wasn't caught earlier. 

If I change the source tsconfig.json to `include` all the files in `dist`, the error goes away. This makes me believe the problem is due to Typescript not applying the tsconfig to the dist folder.

Additionally, changing the import from `@zenfs/core/mixins/shared.js` to `@zenfs/core/dist/mixins/shared.js` fixes the problem.

I will take a closer look at this, but it may take a little longer than usual due to the strangeness of the bug.

**Comment by james-pre** [comment]
@yoursunny,

Could you please try to reproduce the issue with the latest version of `@zenfs/core` (1.0.3)? When you do, make sure the output of `npm ls utilium` shows `utilium@0.7.4`.

**Comment by yoursunny** [comment]
This issue is resolved as of:

```json
{
    "@zenfs/core": "1.0.5",
    "@zenfs/dom": "0.2.17"
}
```
