### ISSUE TITLE
Inode corruption: Root directory is created as a file in `localStorage`

### ISSUE THREAD

**Issue by LePau** [zen-fs/dom#19]
I'm using isomorphic git to clone a repo and IndexedDB works fine, but very slow.  I wanted to compare with WebStorage:localStorage as a backend, but it's complaining that '/' is a file.

Repeatable code:

```typescript
import { configure, Overlay, fs, } from "@zenfs/core";
import { WebStorage } from '@zenfs/dom';

await configure<typeof Overlay>({
    mounts: {
        '/': {
            backend: WebStorage,
            storage: localStorage,
        }
    }
});
console.log((await fs.promises.stat("/")).isDirectory());
```
Outputs:

> false

Should be:

> true

Versions:

* "@zenfs/core": "^1.0.10"
* "@zenfs/dom": "^0.2.17"
* Chrome Version 128.0.6613.137 (Official Build) (64-bit)
* Ubuntu

**Comment by james-pre** [comment]
Ah, I've found the issue! This is due to `@zenfs/core` v1.0.5 changing the encoding and decoding functions to use UTF8 instead of just converting raw. This means the raw binary data of an Inode was interpreted as UTF-8 encoded, and that resulted in invalid parsing.

This has happened before, and I've made some changes in https://github.com/zen-fs/core/commit/7ba27890f334d65e833e1933578bbec126dbaf35 to hopefully prevent regression in the future.

This bug is because [`WebStorageStore`](https://zenfs.dev/dom/classes/WebStorageStore.html) used `decode` and `encode` to convert the data between strings and `Uint8Array`s.

I should have a fix along shortly.

**Comment by james-pre** [comment]
@LePau, [1.0.1](https://github.com/zen-fs/dom/releases/tag/v1.0.1) should fix the bug. Please let me know if everything looks good on your end.

**Comment by james-pre** [comment]
What is the out of `statSync('/')`? What is `fs.mounts.get('/').store.storage` (or more specifically, what are the entries in the store)?

**Comment by LePau** [comment]
statSync('/'):

```
{
  "dev": 0,
  "ino": 1181090081933517000,
  "rdev": 0,
  "nlink": 1,
  "blksize": 4096,
  "uid": 0,
  "gid": 0,
  "atimeMs": 1729348231123,
  "mtimeMs": 1729348231123,
  "ctimeMs": 1729348231123,
  "birthtimeMs": 1729348231123,
  "size": 4096,
  "mode": 16893,
  "_isBigint": false
}
```

fs.mounts.get('/'):
```
{
  "store": {
    "storage": {
      "0": "\u0005ab�+\u0013d\u0010\u0000\u0010\u0000\u0000�A\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00000��R*yB\u00000��R*yB\u00000��R*yB\u00000��R*yB",
      "1181090079869919493": "{}"
    }
  },
  "_initialized": true,
  "_disableSync": false
}
```

**Comment by james-pre** [comment]
Well, the inodes don't match- the root Inode points to `1181090081933517000` while the actual one is `1181090079869919493`. This is yet another strange issue. One problem I see is that `ino` is a regular number, not a bigint, which may be playing a role here.

**Comment by LePau** [comment]
The type of ino is a directory.  Is that what you mean?

**Comment by james-pre** [comment]
The `ino` essentially acts as a pointer. Ino `0` contains an `Inode`, which in turn has an `ino` pointing to the data for that file or directory. In the case of the root directory, this is a JSON-encoded object mapping directory entries to `Inode`s.

**Comment by LePau** [comment]
Hi @james-pre sorry for the late reply.  I don't have much time to work on this unfortunately.  If you'd like you can close it since I'm the only one having the issue.  If I get back to it I will attempt to troubleshoot it and open a PR myself.  Thank you for all the time you've put into it!

**Comment by james-pre** [comment]
@LePau, Thank *you* for opening the issue. You still helped me fix another (unrelated) bug. If you want to open a PR, that would be great. No pressure though.

Some troubleshooting/debugging information you may want to consider:
- Clearing `localStorage` may help, since any corrupted data would be deleted
- You can interact directly with inode serialization using `new Inode(buffer)` and `serialize(inode)`
	- `serialize` comes from [Utilium](https://github.com/james-pre/utilium).
- Inodes use Utilium's structs to do magic with the binary format
